### ISSUE TITLE
Visualization 

### ISSUE THREAD

**Issue by jiefengsun** [GazzolaLab/PyElastica#1]
Hello,

I just want to ask what software you used to visualize the results as done in your papers.  Is it Blender?

**Comment by nmnaughton** [comment]
Hi @jiefengsun, thanks for reaching out! We use POVray for our visualizations and have developed some custom scripts for the command line use of it. However, it does look like POVray can be interfaced with Blender, so that might be a good (maybe even better?) method for visualization.

**Comment by jiefengsun** [comment]
Thanks for the clarification! I asked the question since I found the link to the visualization part was missing. Look forward to seeing your update on that part.

**Comment by nmnaughton** [comment]
Yes, we are behind on that section of the website. We hope to have something posted soon. Thanks for your interest!
