### ISSUE TITLE
CODEOWNERS setup

### ISSUE THREAD

**Issue by bhosale2** [GazzolaLab/PyElastica#102]
For automatic targeted reviewer requests, we should consider having a `CODEOWNERS` file like `https://github.com/tp5uiuc/elasticapp/blob/master/docs/CODEOWNERS`.

**Comment by skim0119** [comment]
I like the idea, but do you think our team is big enough that we need this? We only have 3 active maintainers, and practically we get 1~2 external issues per month.

**Comment by bhosale2** [comment]
Resolved by #115.
