### ISSUE TITLE
A minimal dynamic validation case for PyElastica

### ISSUE THREAD

**Issue by bhosale2** [GazzolaLab/PyElastica#111]
We need a minimal, dynamic validation case for PyElastica, to make validation of the solver against physical problems more rigorous. An example of this could be an oscillating Bernoulli/Timoshenko beam, with reference analytical solutions.

**Comment by armantekinalp** [comment]
@tp5uiuc  suggested this [dynamic validation case](https://journals.sagepub.com/doi/10.1177/0278364919842269). I am dropping the link here for our reference.

**Comment by armantekinalp** [comment]
Closed with #173
