### ISSUE TITLE
Separate joint module into separate connections and collision

### ISSUE THREAD

**Issue by bhosale2** [GazzolaLab/PyElastica#113]
Currently, the implementation for connections and collision lies in `joint.py` which is a rather non-intuitive name for its contents. A more intuitive name could be `connections_and_collision.py`? @armantekinalp and @skim0119 suggestions?

**Comment by skim0119** [comment]
I think `collision` should be separated. I agree that `connection could be more general name.

**Comment by bhosale2** [comment]
Ok, then the consensus on this is:
1. Rename `joint.py` to `connections.py`
2. Move out collision classes into a separate `collision.py`

**Comment by armantekinalp** [comment]
Yes, I think it is a good idea

**Comment by Ali-7800** [comment]
Merging checklist
- [ ] New contact module and tests
- [ ] Updated rod-rod, rod-cylinder, self-contact classes, examples, and tests
- [ ] Surface class, surface subclass: plane, and tests
- [ ] Updated rod-plane, cylinder-plane classes, examples, and tests

**Comment by Rahul-JOON** [comment]
@Ali-7800 added the New Contact module, surface base class, and tests via #281.

**Comment by Ali-7800** [comment]
Added Updated rod-rod, rod-cylinder, self-contact classes, examples, and tests via #291

**Comment by Ali-7800** [comment]
Added the new plane surface subclass.

**Comment by Ali-7800** [comment]
Added updated rod-plane contact class

**Comment by Ali-7800** [comment]
Updated rod-plane contact classes tests and refactored contact functions in interaction.py and joint.py

**Comment by Ali-7800** [comment]
Updated rod-plane contact examples and added continuum snake with lifting wave example

**Comment by Ali-7800** [comment]
Updated documentation for contact module, closing now as issue is resolved
