### ISSUE TITLE
Unused and unnecessary parameters in OneEndFixedBC

### ISSUE THREAD

**Issue by mstoelzle** [GazzolaLab/PyElastica#137]
**Describe the bug**
The documentation of `OneEndFixedBC` clearly describes that the constraint is applied on the first node of the rod. Why does it need then the parameter `constrained_position_idx `, and `constrained_director_idx `. These should only be necessary for the `FixedConstraint` rod. When I look at the control flow, `constrained_position_idx `, and `constrained_director_idx ` are not used anyway. However, a lot (maybe most?) examples even use the syntax below:
```py
simulator.constrain(rod).using(
    OneEndFixedBC,
    constrained_position_idx=(0,),
   constrained_director_idx=(0,)
)
```

**To Reproduce**
```py
class OneEndFixedBC(ConstraintBase):
    """
    This boundary condition class fixes one end of the rod. Currently,
    this boundary condition fixes position and directors
    at the first node and first element of the rod.

    Examples
    --------
    How to fix one ends of the rod:

    >>> simulator.constrain(rod).using(
    ...    OneEndFixedBC,
    ...    constrained_position_idx=(0,),
    ...    constrained_director_idx=(0,)
    ... )
    """

    def __init__(self, fixed_position, fixed_directors, **kwargs):
        """

        Initialization of the constraint. Any parameter passed to 'using' will be available in kwargs.

        Parameters
        ----------
        constrained_position_idx : tuple
            Tuple of position-indices that will be constrained
        constrained_director_idx : tuple
            Tuple of director-indices that will be constrained
        """
        super().__init__(**kwargs)
        self.fixed_position_collection = np.array(fixed_position)
        self.fixed_directors_collection = np.array(fixed_directors)

```

**Environment**
- PyElastica: 0.3.0

**Expected behavior**
Expected syntax would be this:
```py
simulator.constrain(rod).using(
    OneEndFixedBC,
)
```

**Comment by skim0119** [comment]
Just for the record, it is used and it is necessary parameters. You need to pass `-1` to fix another end. It is an alias to `FixedConstraint` for the paper and **legacy purpose**.

#54 Here is the PR.
