### ISSUE TITLE
Enable forcing class init to access the system 

### ISSUE THREAD

**Issue by armantekinalp** [GazzolaLab/PyElastica#140]
**Is your feature request related to a problem? Please describe.**
Current implementation of forcing class does not have access to the `system` during initialization step. However, some of the forcing classes that will be implemented in future will need `system` properties during the initialization step. 

**Describe the solution you'd like**
Make `system` a private member of forcing class.

**Describe alternatives you've considered**
`system` can be provided in `kwargs` of forcing class.

**Comment by bhosale2** [comment]
After discussion with @armantekinalp we decided to not do this since it involves refactoring compared to extending the codebase.
