### ISSUE TITLE
Add ConfigurableFixedConstraint boundary condition class

### ISSUE THREAD

**Issue by mstoelzle** [GazzolaLab/PyElastica#148]
**Is your feature request related to a problem? Please describe.**
Currently, there exists only the option to either have a) no boundary conditions or b) fully fixed boundary conditions. The only functionality in between is that for example translations are allowed, but rotations are constrained and vice-versa. However in practice, there are many situations where we would like to allow certain translations (for example along a plane) or rotations (for example allow yawing of the end of the rod), but constrain all other DoF. The user of the library would have to implement this functionality all themselves inheriting from the `FreeBC` class. In many cases, such an implementation is not straight-forward. Thus, the library should provide the user the option to configure the BC themselves in a simple fashion. Although it obviously will never cover all the edge-cases a specific project might require, it will give the user an idea / hint / guidance on how to implement a similar solution.

**Describe the solution you'd like**
Address missing functionality by adding `ConfigurableFixedConstraint` class:

- Using boolean arrays `translational_constraint_selector` and `rotational_constraint_selector`, the user can specify which Degrees of Freedom to allow / constrain at the specified nodes.
- These boolean arrays have to be specified in the inertial frame.
- The `ConfigurableFixedConstraint` will now only re-set the positions, velocities, directors and omegas to the saved, fixed values for the constrained dimensions. The other DoF are allowed to freely move / rotate.
- We can simplify the codebase by now having `FixedConstraint` be a child class of `ConfigurableFixedConstraint`. `FixedConstraint` will still constrain all dimension, e.g. `translational_constraint_selector=np.array([True, True, True])` and `rotational_constraint_selector=np.array([True, True, True])`

**Describe alternatives you've considered**
Having separate constraint classes for only constraining _x_-translation, _y_-translation, _z_-translation,  _roll_, _pitch_, and _yaw_ one at a time. The user would need to constrain each Degree of Freedom separately. For translations, this might work decently well, but constraining the rotation separately might be very hard to implement through separate classes.

**Questions / Points for discussion**

1. Instead of having hard constraints, should these constraints be formulated in a soft fashion to improve numerical stability of the solver? Could the `FixedJoint` implementation be a template for this? Which base class should be used for that?
2. Which algorithm can we use to allow certain rotations and restrict rotations around other rotation axis? Formulated in a different way: If we have an actual rotation matrix `C_actual` from the initial orientation to the current orientation, how can we find a rotation matrix `C_allowed` which only contains the _allowed_ rotation from the initial orientation? Knowing these two rotation matrices, we could now easily implement hard or soft constraints. Is using euler angles for this purpose a suitable way to go?

**Comment by bhosale2** [comment]
Fixed by #143.
