### ISSUE TITLE
Illustration of cylinders is incorrect

### ISSUE THREAD

**Issue by matei1996** [GazzolaLab/PyElastica#159]
Dear PyElastica Team,

since yesterday my illustration of my experiment changed. I am trying to guide a rod through labyrinth of several cylinders. However, it seems like the basis of cylinders is not circular anymore. It looks more like an ellipsis. I updated my Anaconda(now 4.13.0) and Jupyter Notebook(now 6.4.11) yesterday. I am using a Python3(ipykernel). Maybe this causes the issue. I have attached two example videos. One is older with circular basis, one is new where my described problem can be seen.

Kind regards,
Matei

https://user-images.githubusercontent.com/87129296/181478400-8ad75ce4-437c-42f0-853a-4ad567dd7165.mp4

https://user-images.githubusercontent.com/87129296/181478516-60dc7bdf-5bd0-43ee-96c2-72e9f487d86d.mp4

**Comment by bhosale2** [comment]
@matei1996 can you please post your case file code, the function you use to plot the cylinders, and the code for that function?

**Comment by armantekinalp** [comment]
Also please list the conda environment variables and their version.

**Comment by matei1996** [comment]
The code is below In the first part the function to plot and create videos is defined. The second part generates the rod and cylinders. It is a bit messy, sorry about that

The pdf 
[Conda environment variables.pdf](https://github.com/GazzolaLab/PyElastica/files/9212574/Conda.environment.variables.pdf)
file contains the variables and version (I hope this is what you are asking for)

`
%reset -f
import numpy as np
from matplotlib import pyplot as plt
import cv2
import os

def make_data_for_cylinder_along_y(cstart, cradius, cheight):
    center_x, center_z = cstart[0], cstart[1]
    y = np.linspace(0, cheight, 5)
    theta = np.linspace(0, 2 * np.pi, 20)
    theta_grid, y_grid = np.meshgrid(theta, y)
    x_grid = cradius * np.cos(theta_grid) + center_x
    z_grid = cradius * np.sin(theta_grid) + center_z
    y_grid += cstart[2]
    return [x_grid, y_grid, z_grid]


def plot_video(
    rod_history: dict,
    cylinder_history: dict,
    video_name="video.mp4",
    margin=0.2,
    fps=60,
    step=1,
    *args,
    **kwargs
):  # (time step, x/y/z, node)
    c=-1
    num_cyl=len(cylinder_history)-1
    for item in cylinder_history:
        c=c+1
        #cylinder_radius=cylinder_radius[c]
        #current_cylinder=cylinder_history[c]
        #breakpoint()
        cylinder_start = np.array(item["position"])[0, ...]
        cylinder_radius = kwargs.get("cylinder_radius")[c]
        cylinder_height = kwargs.get("cylinder_height")
        cylinder_direction = kwargs.get("cylinder_direction")

        XC, YC, ZC = make_data_for_cylinder_along_y(
            cylinder_start, cylinder_radius, cylinder_height
        )

        import matplotlib.animation as manimation

        plt.rcParams.update({"font.size": 22})

        # Should give a (n_time, 3, n_elem) array
        positions = np.array(rod_history["position"])
        # (n_time, 3) array
        com = np.array(rod_history["com"])

        cylinder_com = np.array(item["com"])
        cylinder_origin = cylinder_com - 0.5 * cylinder_height * cylinder_direction

        print("plot video")
        FFMpegWriter = manimation.writers["ffmpeg"]
        metadata = dict(title="Movie Test", artist="Matplotlib", comment="Movie support!")
        writer = FFMpegWriter(fps=fps, metadata=metadata)
        dpi = 50

        # min_limits = np.roll(np.array([0.0, -0.5 * cylinder_height, 0.0]), _roll_key)
        from mpl_toolkits.mplot3d import Axes3D

        fig = plt.figure(1, figsize=(10, 8), frameon=True, dpi=dpi)
        ax = plt.axes(projection="3d")  # fig.add_subplot(111)
        ax.grid(visible=True, which="minor", color="k", linestyle="--")
        ax.grid(visible=True, which="major", color="k", linestyle="-")
        plt.axis("off")

        i = 0
        if c==num_cyl:
            (rod_line,) = ax.plot(positions[i, 0], positions[i, 1], positions[i, 2], lw=3.0)
        XC, YC, ZC = make_data_for_cylinder_along_y(
            cylinder_origin[i, ...], cylinder_radius, cylinder_height
        )
        surf = ax.plot_surface(XC, YC, ZC, color="g", alpha=0.5)
        ax.set_xlabel("x")
        ax.set_ylabel("y")
        ax.set_zlabel("z")

        min_limits = np.array([0.0, 0.0, -0.5 * cylinder_height])
        min_limits = -np.abs(min_limits)
        max_limits = min_limits + cylinder_height

        ax.set_xlim([min_limits[0], max_limits[0]])
        ax.set_ylim([min_limits[1], max_limits[1]])
        ax.set_zlim([min_limits[2], max_limits[2]])
        with writer.saving(fig, video_name, dpi):
            with plt.style.context("seaborn-white"):
                for i in range(0, positions.shape[0], int(step)):
                    if c==num_cyl:
                        rod_line.set_xdata(positions[i, 0])
                        rod_line.set_ydata(positions[i, 1])
                        rod_line.set_3d_properties(positions[i, 2])
                    XC, YC, ZC = make_data_for_cylinder_along_y(
                        cylinder_origin[i, ...], cylinder_radius, cylinder_height
                    )
                    surf.remove()
                    surf = ax.plot_surface(XC, YC, ZC, color="g", alpha=0.5)
                    writer.grab_frame()

        from matplotlib.patches import Circle

        fig = plt.figure(2, figsize=(10, 8), frameon=True, dpi=dpi)
        ax = fig.add_subplot(111)
        i = 0
        cstart = cylinder_origin
        if c==num_cyl:
            (rod_line,) = ax.plot(positions[i, 0], positions[i, 1], lw=3.0)
            (tip_line,) = ax.plot(com[i, 0], com[i, 1], "k--")

        min_limits = np.array([0.0, 0.0, -0.5 * cylinder_height])
        max_limits = min_limits + cylinder_height

        ax.set_xlim([min_limits[0], max_limits[0]])
        ax.set_ylim([min_limits[2], max_limits[2]])

        circle_artist = Circle((cstart[i, 0], cstart[i, 2]), cylinder_radius, color="g")
        ax.add_artist(circle_artist)
        plt.axis("off")
        
    ax.set_aspect("equal")
    video_name = "2D_" + video_name
    with writer.saving(fig, video_name, dpi):
        with plt.style.context("fivethirtyeight"):
            for i in range(0, positions.shape[0], int(step)):
                if c==num_cyl:
                    rod_line.set_xdata(positions[i, 0])
                    rod_line.set_ydata(positions[i, 2])
                    tip_line.set_xdata(com[:i, 0])
                    tip_line.set_ydata(com[:i, 2])
                circle_artist.center = cstart[i, 0], cstart[i, 2]
                writer.grab_frame()


def plot_cylinder_rod_position(
    rod_history,
    cylinder_history,
    cylinder_radius,
    rod_base_radius,
    TIP_COLLISION,
    TIP_CHOICE,
    _roll_key=0,
):
    c=-1
    for item in cylinder_history:
        c=c+1
        #current_cylinder=cylinder_history[c]
        cylinder_start = np.array(item["position"])[0, ...]
        positions = np.array(rod_history["position"])
        sim_time = np.array(rod_history["time"])

        n_elem = positions.shape[-1]

        fig = plt.figure(figsize=(10, 8), frameon=True, dpi=150)
        plt.rcParams.update({"font.size": 18})
        ax = fig.add_subplot(111)
        colliding_element_idx = n_elem // 2
        if TIP_COLLISION:
            colliding_element_idx = 0 if TIP_CHOICE == 1 else -1
        colliding_element_history = positions[:, :, colliding_element_idx]
        # fig = plt.figure(3, figsize=(8, 5))
        # ax = fig.add_subplot(111)
        ax.plot(sim_time, colliding_element_history[:, _roll_key], label="rod")
        ax.hlines(
            cylinder_start[_roll_key] - cylinder_radius[c] - rod_base_radius,
            sim_time[0],
            sim_time[-1],
            "k",
            linestyle="dashed",
            label="cylinder",
        )
        plt.xlabel("Time [s]", fontsize=20)
        plt.ylabel("Position", fontsize=20)
        fig.legend(prop={"size": 20})
        #plt.axis("off")
        plt.show()

import numpy as np

# FIXME without appending sys.path make it more generic
import sys

sys.path.append("../../../")
from elastica import *
#from post_processing import plot_video, plot_cylinder_rod_position


class SingleRodSingleCylinderInteractionSimulator(
    BaseSystemCollection, Constraints, Connections, Forcing, CallBacks
):
    pass


# Options
PLOT_FIGURE = True

single_rod_sim = SingleRodSingleCylinderInteractionSimulator()
# setting up test params
n_elem = 50

inclination = np.deg2rad(30)
#direction = np.array([0.0, np.sin(inclination), -np.cos(inclination)])
#normal = np.array([0.0, np.cos(inclination), np.sin(inclination)])
direction = np.array([1, 0.0, 0.0])
normal = np.array([0.0, 0.0, 1])

base_length = 1
base_radius = 0.01
base_area = np.pi * base_radius ** 2
density = 500
nu = 0.001
E = 1e1
poisson_ratio = 0.5
shear_modulus = E / (1 + poisson_ratio)

cylinder_start = np.array([0.35, 0.0, -0.14])
cylinder_direction = np.array([0.0, 1.0, 0.0])
cylinder_normal = np.array([0.0, 0.0, 1.0])

cylinder_height = 0.9
cylinder_radius = 10.0 * base_radius

# can be set to True, checks collision at tips of rod
TIP_COLLISION = False

# Cylinder surface starts at 0.2
tip_offset = 0.0

TIP_CHOICE = 1
if TIP_COLLISION:
    # The random choice decides which tip of the rod intersects with cylinder
    TIP_CHOICE = np.random.choice([1, -1])
    tip_offset = 0.5 * TIP_CHOICE * base_length * np.cos(inclination)

start_rod_1 = np.array(
    [
        #0.0,
        #0.5 * cylinder_height - 0.5 * base_length * np.sin(inclination),
        #0.5 * base_length * np.cos(inclination) + tip_offset-0.15,
        -0.8,
        0.4,
        -0.07,
    ]
)
# start_rod_1[2] = cylinder_radius + base_length

#start = np.array([-0.2, 0.0, 0.1])
#direction = np.array([0.0, 0.0, 1.0])
#normal = np.array([0.0, 1.0, 0.0])

rod1 = CosseratRod.straight_rod(
    n_elem,
    start_rod_1,
    direction,
    normal,
    base_length,
    base_radius,
    density,
    nu,
    E,
    shear_modulus=shear_modulus,
)
# Give it an initial push
rod1.velocity_collection[0, ...] = 0.05
single_rod_sim.append(rod1)

density_rod=10

cylinder = Cylinder(
    cylinder_start,
    cylinder_direction,
    cylinder_normal,
    cylinder_height,
    cylinder_radius,
    density_rod*100,
)

cylinder_2_start = np.array([0.48, 0.0, 0.05])
cylinder_2_direction = np.array([0.0, 1.0, 0.0])
cylinder_2_normal = np.array([0.0, 0.0, 1.0])
cylinder_radius_2=cylinder_radius*1.1


cylinder_2 = Cylinder(
    cylinder_2_start,
    cylinder_2_direction,
    cylinder_2_normal,
    cylinder_height,
    cylinder_radius_2,
    density_rod*100,
)

cylinder_3_start = np.array([0.6, 0.0, -0.2])
cylinder_3_direction = np.array([0.0, 1.0, 0.0])
cylinder_3_normal = np.array([0.0, 0.0, 1.0])
cylinder_radius_3=cylinder_radius*1.4


cylinder_3 = Cylinder(
    cylinder_3_start,
    cylinder_3_direction,
    cylinder_3_normal,
    cylinder_height,
    cylinder_radius_3,
    density_rod*100,
)


single_rod_sim.append(cylinder)
single_rod_sim.append(cylinder_2)
single_rod_sim.append(cylinder_3)

single_rod_sim.connect(rod1, cylinder).using(ExternalContact, 1e-2, 0.1)
single_rod_sim.connect(rod1, cylinder_2).using(ExternalContact, 1e-2, 0.1)
single_rod_sim.connect(rod1, cylinder_3).using(ExternalContact, 1e-2, 0.1)


# Add call backs
class PositionCollector(CallBackBaseClass):
    """
    Call back function for continuum snake
    """

    def __init__(self, step_skip: int, callback_params: dict):
        CallBackBaseClass.__init__(self)
        self.every = step_skip
        self.callback_params = callback_params

    def make_callback(self, system, time, current_step: int):
        if current_step % self.every == 0:
            self.callback_params["time"].append(time)
            # Collect only x
            self.callback_params["position"].append(system.position_collection.copy())
            self.callback_params["com"].append(system.compute_position_center_of_mass())
            return


recorded_rod_history = defaultdict(list)
single_rod_sim.collect_diagnostics(rod1).using(
    PositionCollector, step_skip=200, callback_params=recorded_rod_history
)
recorded_cyl_history = defaultdict(list)
single_rod_sim.collect_diagnostics(cylinder).using(
    PositionCollector, step_skip=200, callback_params=recorded_cyl_history
)
recorded_cyl_history_2 = defaultdict(list)
single_rod_sim.collect_diagnostics(cylinder_2).using(
    PositionCollector, step_skip=200, callback_params=recorded_cyl_history_2
)
recorded_cyl_history_3 = defaultdict(list)
single_rod_sim.collect_diagnostics(cylinder_3).using(
    PositionCollector, step_skip=200, callback_params=recorded_cyl_history_3
)

single_rod_sim.finalize()
timestepper = PositionVerlet()
final_time = 10.0
dl = base_length / n_elem
dt = 1e-4
total_steps = int(final_time / dt)
print("Total steps", total_steps)

all_cylinders=[recorded_cyl_history,recorded_cyl_history_2,recorded_cyl_history_3]
cylinder_radius_test=[cylinder_radius,cylinder_radius_2,cylinder_radius_3]

integrate(timestepper, single_rod_sim, final_time, total_steps)

if PLOT_FIGURE:
    plot_video(
        recorded_rod_history,
        #recorded_cyl_history_2,
        all_cylinders,
        "cylinder_rod_collision.mp4",
        cylinder_direction=cylinder_direction,
        cylinder_height=cylinder_height,
        cylinder_radius=cylinder_radius_test,
    )

    plot_cylinder_rod_position(
        recorded_rod_history,
        #recorded_cyl_history_2,
        all_cylinders,
        cylinder_radius=cylinder_radius_test,
        rod_base_radius=base_radius,
        TIP_COLLISION=TIP_COLLISION,
        TIP_CHOICE=TIP_CHOICE,
    )
`

**Comment by skim0119** [comment]
@matei1996 I briefly looked, and I don't see any issue in the code other than figsize is not square. I would say try to set the axis to be the equal length in both x and y (set aspect ratio to be 1), and leave an issue to Matplotlib if the problem remains.

**Comment by matei1996** [comment]
Setting the aspect ratio to 1 solved the problem. Thanks for the help! I am closing the issue.
