### ISSUE TITLE
Cross-check and modify if needed joint damping force direction

### ISSUE THREAD

**Issue by armantekinalp** [GazzolaLab/PyElastica#164]
As pointed out in PR #149 damping force direction sign should be opposite 

https://github.com/GazzolaLab/PyElastica/blob/d0cb959ab6ac328fd518fa846f8edf2ea164992f/elastica/joint.py#L92

Correct implementation should be

```python
 damping_force = self.nu * normal_relative_velocity 
```

**Comment by bhosale2** [comment]
Closed via #170.
