### ISSUE TITLE
🔥 Bump up python version for ReadTheDocs

### ISSUE THREAD

**Issue by skim0119** [GazzolaLab/PyElastica#178]
**Describe the bug**
Within RTD, documentation is built using python 3.7, and the build is failing.

**Details**
We are slowly adopting the `typing` and `Protocol` module, which is included in version 3.8+. Previously, `Protocol` was in `typing_extensions`.

**What to do**
Modify `.readthedocs.yaml` to install package using poetry. This should be resolved before merging v0.3.

**Reference**
https://github.com/GazzolaLab/MiV-OS/blob/main/.readthedocs.yaml

**Comment by skim0119** [comment]
[![Documentation Status](https://readthedocs.org/projects/pyelastica/badge/?version=update-0.3.0)](https://docs.cosseratrods.org/en/update-0.3.0/?badge=update-0.3.0)

**Comment by armantekinalp** [comment]
fixed with [6c8e518](https://github.com/GazzolaLab/PyElastica/commit/6c8e518e24b6bccfc9be5917738aa7de95716a4a)
