### ISSUE TITLE
Clarify namespace for elastica modules to avoid namespace confusion and clutter

### ISSUE THREAD

**Issue by bhosale2** [GazzolaLab/PyElastica#193]
Currently, in example cases, the modules from `elastica` are imported directly as `from elastica import *`. This can become an issue when using `elastica` across packages (where `elastica` is a plugin), where modules from other packages can collide in namings with the modules from `elastica`. To avoid this, it may be helpful to use functionalities in `elastica` as:

`import elastica as ea; ea.Damping(....)` to make it explicit where the functionality comes from.

@skim0119 and @armantekinalp thoughts?

**Comment by armantekinalp** [comment]
I think it is a good suggestion.

**Comment by skim0119** [comment]
Last point on [pep8](https://peps.python.org/pep-0008/#imports)

**Comment by prabhashj07** [comment]
Is this issue open?
I'm a beginner and I'd like to work on it.

**Comment by armantekinalp** [comment]
Yes it is still open

**Comment by Rahul-JOON** [comment]
If this issue is still open, I would like to be assigned to it.

**Comment by Deep-Rai-08** [comment]
Is this issue is open?? @armantekinalp

**Comment by skim0119** [comment]
@Deep-Rai-08 The issue is still open. Feel free to make a PR.

**Comment by bhosale2** [comment]
A note to everyone interested in this issue: if you plan to work on it please either assign yourself to the issue or let us know that you wish to be assigned to the issue.

**Comment by amangupta201** [comment]
NameSpaces can be a great way to sort and clarify the elastica modules
Please assign me to this issue

**Comment by AsadNizami** [comment]
Hi, is anyone still working on the issue? If not I'd like to work on it.

**Comment by bhosale2** [comment]
Closed via #238.
