### ISSUE TITLE
Remove the option for internal damping module for Cosserat rods following warning message

### ISSUE THREAD

**Issue by bhosale2** [GazzolaLab/PyElastica#194]
Currently, adding damping to the rod via `AnalyticalLinearDamper` results in the following warning message:

<img width="1394" alt="Screen Shot 2022-08-30 at 10 02 31 PM" src="https://user-images.githubusercontent.com/33580851/187583366-ed956e50-573e-48d5-ac66-8b10c015df01.png">

Per the warning to make a soft change, we should convert the warning message to an error message if the user provides internal damping other than `None` when initializing a Cosserat rod, and remove related functionality from the cosserat rod equations.

Thoughts @armantekinalp and @skim0119?

**Comment by armantekinalp** [comment]
I agree with you suggestion. As we discussed with @bhosale2, I think we should remove the internal damping functionality, all variables and tests as we planned in `v.0.3.1` and update the warning message accordingly.

**Comment by bhosale2** [comment]
Closed via #243.
