### ISSUE TITLE
ModuleNotFoundError__No Module named 'examples'

### ISSUE THREAD

**Issue by LegendCC-Zhang** [GazzolaLab/PyElastica#204]
Dear all, I used anaconda as envs to pip install pyelastica, and then I tried to do  some examples given here.

But here some issues occurred, ModuleNotFoundError: No module named "examples". And then I found that we need do “make install_examples_dependencies” first, but I do not know how to do it.
![1](https://user-images.githubusercontent.com/101251204/195993356-65c7ff53-f9d6-437d-a986-a67452930dcb.png)
![2](https://user-images.githubusercontent.com/101251204/195993363-7554d9c9-05ce-4fca-b631-88bc8e152fb3.png)

**Comment by LegendCC-Zhang** [comment]
Looking forward to your help! Thank you in advance!

**Comment by bhosale2** [comment]
@LegendCC-Zhang can you please provide more information on this issue? For instance which example did you try to run? Did you run the python example script or the jupyter notebook example?

**Comment by LegendCC-Zhang** [comment]
> 
Thanks for your reply! 

I used anaconda to create an env.
![windows](https://user-images.githubusercontent.com/101251204/196013459-34ee5676-2534-465b-9de2-d61ade58e438.png)
, then "pip install pyelastica", and then used jupyter notebook to run the examples. 
For the examples, such as "[timoshenko_postprocessing.py](https://github.com/GazzolaLab/PyElastica/blob/master/examples/TimoshenkoBeamCase/timoshenko_postprocessing.py)" that require import example module, error occurs at my end. 
I have two laptops, the OS of which are Windows and Linux, respectively. But I failed to do the "make install_examples_dependencies", as stated in the readme shown in the examples file (https://github.com/GazzolaLab/PyElastica/tree/master/examples).
The attached file is the pip list based on Windows-anaconda-pyelastica  env.
So, could you please help on this issue?

Thanks!

**Comment by armantekinalp** [comment]
@LegendCC-Zhang can you follow these steps

1. Please clone the code and `cd` inside the cloned directory
2. Do `make poetry-download`
3. Do `make install`
4. Do `make install_example_dependencies`
5. `pip install pyelastica`
6. Then please run `python examples/TimoshenkoBeamCase/timoshenko.py `

Let me know if you have any problems.
