### ISSUE TITLE
"install_examples_dependencies" file is missing

### ISSUE THREAD

**Issue by saultshaker** [GazzolaLab/PyElastica#216]
Hi, 

I noticed in the documentation in the README for the [examples folder](https://github.com/GazzolaLab/PyElastica/tree/master/examples), under the "Installing Requirements" section, there is mention of a "install_examples_dependencies"  to be run with "make install_examples_dependencies".  

However, I can't seem to find a file called  "install_examples_dependencies" anywhere. 

Thanks for your time!

**Comment by armantekinalp** [comment]
Hi @saultshaker ,

You need to run `make install_examples_dependencies` dependencies at the `PyElastica` folder where `Makefile` is located and not inside `PyElastica/examples/`

**Comment by saultshaker** [comment]
Thank you! This resolved my issue :)

**Comment by bhosale2** [comment]
Closing since resolved.
