### ISSUE TITLE
Static Solution

### ISSUE THREAD

**Issue by fepauly** [GazzolaLab/PyElastica#218]
Hi,

I'm currently looking into different tools to do static and dynamic analysis of cosserat rods. 
Hence my question: Is it possible to do static analysis with PyElastica without time integration? And if not, is it possible without too much effort to include this feature with additional code by myself without manipulating PyElastica itself?

Thank you for your feedback.
Bests

**Comment by armantekinalp** [comment]
PyElastica does not have a feature for static analysis. For that I think, you would need to implement an iterative solver. Cosserat Rod equations are already implemented but you need to write rest of the code.

**Comment by fepauly** [comment]
Hi,

Thank you for your reply.

**Comment by skim0119** [comment]
I'm closing this issue. Please re-open if you have further question.
