### ISSUE TITLE
Code in getting started guide doesn't work

### ISSUE THREAD

**Issue by davenpi** [GazzolaLab/PyElastica#22]
Hi all, 

Thanks for writing the package! I'm just getting started and trying to test a few things out but the code from the [getting started guide](https://www.cosseratrods.org/software/pyelastica/) doesn't run. The code in the guide has a few syntactical errors (missing equals signs) but more importantly it seems that the API has changed a bit and isn't reflected in the docs. 
<img width="1127" alt="Screen Shot 2021-10-14 at 3 22 20 PM" src="https://user-images.githubusercontent.com/49379192/137382206-25db0177-5265-492f-a6cf-691a017c8b00.png">
.

**Comment by armantekinalp** [comment]
@davenpi  I run the Slithering Snake example notebook on [binder](https://mybinder.org/v2/gh/GazzolaLab/PyElastica/master?filepath=examples%2FBinder%2F0_PyElastica_Tutorials_Overview.ipynb) and it outputs a snake velocity plot and a video showing the snake motion. Where did you run the notebook?

**Comment by davenpi** [comment]
I'm running it in a Colab notebook. Everything before the screenshot works. The problem is the "analysis functions" import in the `compute_and_plot_velocity` function. My thinking was that this notebook should generate plots in a self contained manner but it seems that I need to define my own module to make this work. Is that correct?
<img width="760" alt="Screen Shot 2021-10-15 at 7 46 03 PM" src="https://user-images.githubusercontent.com/49379192/137564990-98ecf23f-176d-49e4-88ef-79c3b2b59032.png">
.

**Comment by armantekinalp** [comment]
#24
