### ISSUE TITLE
Code for octopus arm

### ISSUE THREAD

**Issue by zixichen007115** [GazzolaLab/PyElastica#223]
I find the paper "Energy Shaping Control of a CyberOctopus Soft Arm" in the case studies. Could you please tell me whether there is existing code in this repository for this paper?

**Comment by armantekinalp** [comment]
Hi @zixichen007115 

Code related to the "Energy Shaping Control of a CyberOctopus Soft Arm" is in [COOMM](https://github.com/hanson-hschang/COOMM) repository and it uses PyElastica as dependency.
