### ISSUE TITLE
Possible Bug: Test restart functionality and applying constrains 

### ISSUE THREAD

**Issue by armantekinalp** [GazzolaLab/PyElastica#239]
We should test the below line in the restart code. We suspect it creates incorrect results, when we load and time-step.

https://github.com/GazzolaLab/PyElastica/blob/7b3fe2d0204a175c9e5e64265c70b9577b4ca8c9/elastica/restart.py#L92-L93

**Comment by bhosale2** [comment]
Fixed by #249.
