### ISSUE TITLE
Binder is not working with Poetry

### ISSUE THREAD

**Issue by armantekinalp** [GazzolaLab/PyElastica#282]
**Describe the bug**
Binder examples for PyElastica does not run on the server, because MyBinder requires a `requirement.txt` file and PyElastica uses poetry as the dependency manager. [Here](https://mybinder.readthedocs.io/en/latest/examples/sample_repos.html) are the some example Binder repositories that might be useful to find a work around.

**Comment by bhosale2** [comment]
@armantekinalp two suggestions maybe from my side:

1. Have a `requirements.txt` on the main repo and use that (many Python packages I saw keep multiple dependency manager files that include `requirements.txt`, `env.yaml` for conda, etc)
2. Call `poetry` at the start of notebook to export toml as `requirements.txt` file?

**Comment by bhosale2** [comment]
@armantekinalp please assign the appropriate priority here

**Comment by armantekinalp** [comment]
Maybe collar

**Comment by Ali-7800** [comment]
Closing as issue is solved
