### ISSUE TITLE
Issue with Plectoneme_case example

### ISSUE THREAD

**Issue by AkashVardhan7** [GazzolaLab/PyElastica#285]
Hi I was running the plectoneme_case example, and the code crashed after generating videos, at the compute_twist function. Here's a screenshot.
![image](https://github.com/GazzolaLab/PyElastica/assets/48886152/9b72bd64-27be-493a-a03b-a817b33751d4)

**Comment by armantekinalp** [comment]
Can you share the list of packages you installed in your environment? I suspect this is something local in your settings. Two of us able to run this example without an issue.

**Comment by armantekinalp** [comment]
We have resolved this issue, but haven't pushed to the main branch yet. It will be pushed in our next release cycle. However, you can still run the example.  Checkout `update-0.3.2` branch and run the example with that.
