### ISSUE TITLE
Support for Python 3.11

### ISSUE THREAD

**Issue by biskupds** [GazzolaLab/PyElastica#286]
Hi --

Is there any reason why this package is not supported for Python 3.11? I'm suspecting it is due to the numba/LLVM, but they are now supporting 3.11 after v0.56.

Thank you

**Comment by bhosale2** [comment]
Hi @biskupds, you are right–we were waiting for `numba` to support 3.11 which seems to be the case now. We will soon get to this and release support for 3.11 in the upcoming release.

@biskupds you are welcome to contribute to this repository and open a PR that resolves this issue.

**Comment by bhosale2** [comment]
@biskupds support for Python 3.11 has been added via #307. Closing this as of now.
