### ISSUE TITLE
Is there a cpp version of this library?

### ISSUE THREAD

**Issue by xarthurx** [GazzolaLab/PyElastica#29]
Hi, I'm developing a research project and found this library.
However, I'm doing mainly cpp and need a lib to be able to integrate it into the current system.

After checking the code, it seems the main lib is written in python?
Or do you have another version that is written in C/C++ elsewhere?

Thank you

**Comment by tp5uiuc** [comment]
Hey @xarthurx, thanks for the question.

We are currently developing a C++ version of Elastica, but it's not been released to the public yet. We expect a release sometime soon, in a couple of months. 

Meanwhile, if you really need a code that simulates Cosserat rods, please have a look at the (older) version of [Elastica here](https://github.com/mattialab/elastica). It's written in C++ and maybe what you are looking for.

**Comment by xarthurx** [comment]
@tp5uiuc  Thank you for the info.
I checked the original version (non-HPC). It seems it is only tested on Mac and Linux.

Though I can make it work in Windows, I would suggest that you provide the library in CMake system that can be easily imported as a cross-platform library.

**Comment by tp5uiuc** [comment]
Thanks for the suggestion @xarthurx, we will keep that in mind. I am closing the issue, feel free to reopen if you have more questions.

**Comment by xarthurx** [comment]
@tp5uiuc  I'm currently developing a project that would need a simulator like this.
Would it be possible to have early access to the new version and contribute to it as well?
I've developed several projects for published CG papers, and am quite familiar with cpp.

(Asking because I don't want to integrate the old one just a few months before your new release...)

**Comment by tp5uiuc** [comment]
@xarthurx Let me get back to you on that. I would be happy to share it immediately if I was the only stakeholder. But I need to consult with my advisor first. Hope you understand :)

**Comment by xarthurx** [comment]
@tp5uiuc  Any update on this?

**Comment by tp5uiuc** [comment]
Hey @xarthurx, thanks for waiting. We are finishing up the package now (it's not entirely done), and I estimate it to take some time between 5-7 weeks. My advisor first wants to see a pre-print from our side before releasing the package, so I don't have full autonomy on the package release. So, if possible, can you please wait for the time mentioned? Thanks for understanding :)

**Comment by xarthurx** [comment]
OK, then I may start to use the old one first…
Thanks for the update.

**Comment by IasonManolas** [comment]
Hi are there any updates regarding the c++ release of the library?

**Comment by skim0119** [comment]
@IasonManolas We are planning to release within 1~2 month.
