### ISSUE TITLE
Simulate - redefine loads - simulate

### ISSUE THREAD

**Issue by axla-io** [GazzolaLab/PyElastica#292]
Hi,

I want to do a program that does these tasks:

1. Simulate a rod system forward in time
2. Update the loads acting on the rod system
3. Simulate the system again using the previous last time point as initial state.

How can I do this?

**Comment by armantekinalp** [comment]
Hi @axla-io 

I suggest you to start looking examples and documentations we have to understand how to construct a simulation. You can do all these in PyElastica and examples will be enough to get you started.

**Comment by axla-io** [comment]
Hi @armantekinalp and thanks for the reply! I found what I needed in the restart example.
