### ISSUE TITLE
Updating muscle forces mid-simulation - how does it work?

### ISSUE THREAD

**Issue by saultshaker** [GazzolaLab/PyElastica#311]
I am trying to build a custom gymnasium environment for my own RL project using PyElastica.

I've been digging into the [`muscle_torques_with_bspline.py`](https://github.com/GazzolaLab/Elastica-RL-control/blob/1e708f889b81c572ba4d78d2df7213688e0e7ee3/Case3/ReacherSoft_Case3_main-text/MuscleTorquesWithBspline/BsplineMuscleTorques/muscle_torques_with_bspline.py#L11) for Case 1 to try and understand the nuts and bolts of how muscle torques are changing mid-simulation. 

In an attempt to compare it with a PyElastica example were forces/torques applied to rods aren't changing throughout the simulation, I looked at [`axial_stretching.py`](https://github.com/GazzolaLab/PyElastica/blob/master/examples/AxialStretchingCase/axial_stretching.py) which brought me to the [EndPointForces class](https://github.com/GazzolaLab/PyElastica/blob/11fe8e96ac78fdc1fa4d0ce5bf61bb427afb8875/elastica/external_forces.py#L119). 

I am still not clear how `muscle_torques_with_bspline.py` allows for an RL agent to change the torques within a rod while the simulation is running. Could this be explained?

I'm happy to provide additional details to clarify my question if that's useful. 

Thanks in advance! 

**Additional context**
I posted a [similar comment](https://github.com/GazzolaLab/Elastica-RL-control/issues/11) to the Elastica-RL-control repo, but figured it might be more appropriate here.

**Comment by Ali-7800** [comment]
I replied in to this in https://github.com/GazzolaLab/Elastica-RL-control/issues/11.
