### ISSUE TITLE
How to using PyElastica data to visualize in 3D models? 

### ISSUE THREAD

**Issue by Junang-Wang** [GazzolaLab/PyElastica#318]
Hi,

I've been learning a lot about PyElastica from the community over the past few weeks as a beginner. After simulating my data with PyElastica, I'm wondering how to visualize it in 3D, similar to the nice figures and movies on the PyElastica homepage. Does anyone know which software and Python package is used for this? 

Thank you in advance!
<img width="356" alt="image" src="https://github.com/GazzolaLab/PyElastica/assets/89964840/68f09979-7ff6-483f-97e7-dc66e0167985">

**Comment by armantekinalp** [comment]
You can use Poverty software. Here is the link https://www.povray.org

Also we have an example for how to do it here is the link https://github.com/GazzolaLab/PyElastica/tree/master/examples/Visualization
