### ISSUE TITLE
Bug and fix in 2_Slithering_Snake.ipynb

### ISSUE THREAD

**Issue by TenguBoss** [GazzolaLab/PyElastica#329]
Aloha Elastica Team.

Thank you for posting Jupyter notebooks. 

The loop in `compute_projected_velocity()` is one too long. I have changed line 22 from 
`# for i in range(1, number_of_period - 1):`
to
`for i in range(1, number_of_period - 2):`
to fix it.

Regards,
BU

**Comment by Ali-7800** [comment]
@TenguBoss Thanks for letting us know about this, we fixed the bug and fix would be released with the next update
