### ISSUE TITLE
[GSOC project 3] Binding PyElastica with Elastica++

### ISSUE THREAD

**Issue by ankith26** [GazzolaLab/PyElastica#336]
Hello!

I am opening this issue to discuss Project 3 mentioned in https://github.com/GazzolaLab/PyElastica/discussions/326

I have some prior experience with contributing to some open source projects, but I hope to expand my knowledge and experience by engaging with more projects new to me. I'm quite interested in this task, as I feel like I have the required skills to work on this.

Just a couple of things, before I make my formal proposal document
1. If my understanding is correct, the project `Elastica++` mentioned in the linked discussion is https://github.com/mattialab/elastica (please correct me if I'm mistaken)
2. I'd also like to know whether the entire library is to be binded to python, or only a subset of it
3. pybind11 does not seem to support `Py_LIMITED_API`. So, using this approach will mean that a separate wheel for every python version supported will have to be released, per supported platform. Alternative approaches that could be considered are writing C extensions manually with `Py_LIMITED_API` or using something like [`HPy`](https://github.com/hpyproject/hpy). Both these approaches will be more time-consuming to implement, and also could have a small runtime performance cost. However they will save build time and reduce overall release size.

These are also some related things that I'd like to work on, if accepted
1. Adding type stubs and stub testing for it. Relevent projects that could be useful: [`pybind11-stubgen`](https://github.com/sizmailov/pybind11-stubgen), [mypy stubgen](https://mypy.readthedocs.io/en/stable/stubgen.html) and [mypy stubtest](https://mypy.readthedocs.io/en/stable/stubtest.html)
2. Updating CI to build and test against various python versions (if going the pybind11 way). Relevant project that could be useful: [`cibuildwheel`](https://github.com/pypa/cibuildwheel)
3. Updating docs/tests/examples as per need.

Thanks!

**Comment by bhosale2** [comment]
Hi @ankith26

Please submit your GSOC ideas on the discussion page, not in the issues. Hence, we are closing this issue.
