### ISSUE TITLE
Visualization

### ISSUE THREAD

**Issue by adoroud** [GazzolaLab/PyElastica#4]
Hi,

What is the class or commands for the octopus visualization? does Elastica (PyElastica) have an environment for the visualization part? I could not find anything in your examples providing the same outputs as in the case studies.

Thanks,

**Comment by nmnaughton** [comment]
Hi @adoroud, 

We have not yet released any visualization scripts. We are preparing an update to be released soon and hope to include some there.

**Comment by adoroud** [comment]
> Hi @adoroud,
> 
> We have not yet released any visualization scripts. We are preparing an update to be released soon and hope to include some there.

Thank you for your reply,
Azadeh

**Comment by nmnaughton** [comment]
Hi @adoroud 

We just released a new version of PyElastica with an example script for how we do our visualizations. It is located [here]
(https://github.com/GazzolaLab/PyElastica/tree/master/examples/Visualization). Hope this is helpful!

**Comment by adoroud** [comment]
Hi,

Thanks a lot for informing me.

Best,
Azadeh
