### ISSUE TITLE
Feasibility of Integrating Rigid URDF Models with Flexible Components in PyElastica for Hybrid Robot Simulation

### ISSUE THREAD

**Issue by xuexiqianggai** [GazzolaLab/PyElastica#432]
I am interested in creating a simulation model for a hybrid rigid-flexible robot. My approach involves importing the rigid body model from a URDF file into Python and then using PyElastica to model the flexible parts. The final goal is to connect these rigid and flexible components to complete the robot model.

Could you please advise whether this approach is feasible using PyElastica? If so, are there any recommendations or considerations for implementing this setup?

Thank you for your assistance.

**Comment by Ali-7800** [comment]
Hi @xuexiqianggai,

We don't have the capability of connecting rigid bodies with rods yet, but we currently working on implementing that. I don't have an estimate of when it will be done, but if you want anything soon you might want to consider other options or try to implement a simple connection class yourself.

Let me know if you have other questions.
