### ISSUE TITLE
Recommonmark is deprecated: We should switch to MyST

### ISSUE THREAD

**Issue by skim0119** [GazzolaLab/PyElastica#52]
## Context
We are currently using `sphinx` and `ReadtheDocs` to keep our documentation clean and organized. Natively, `sphinx` uses `reStructuredText` (or .rst extension), and the module `recommonmark` has been used to parse `markdown` format. I ​recently found that the module `recommonmark` is no longer maintained, and the developer (and community) shifted to `MyST` parser.

##  Suggestion
I don't think the issue is imminent and we can probably handle the problem in the back, but I can definitely see the community and the supports for the `markdown` + `sphinx` are shifting to `MyST`. It appears to me that `MyST` is now officially supported `markdown` extension for `sphinx`, and we should change our environment as well.

### Change
It looks like `MyST` is fairly easy to use just like `recommonmark`. Most of the change will be done on `conf.py`, and everything should be compatible.

## Notes

[Deprecation note from recommonmark](https://github.com/readthedocs/recommonmark/issues/221)

**Comment by skim0119** [comment]
Working on my [local branch](https://github.com/skim0119/PyElastica/tree/docs_myst).

I'm going to run few test and make sure documentations are properly generated, and merge to `doc_patch` branch.

**Comment by nmnaughton** [comment]
Just so I am clear, with this patch we would need to convert all the *.rst files to *.md? (It looks like we can do that automatically.) I think having all of the docs page in markdown would work better anyway, so this seems like a  worthwile patch to push through.

**Comment by skim0119** [comment]
@nmnaughton We can still use rst. We don't need to convert.
