### ISSUE TITLE
Increase significant digits of shear coefficient

### ISSUE THREAD

**Issue by armantekinalp** [GazzolaLab/PyElastica#79]
Shear coefficient for circular cross-section can be computed as `27/28` using the formula given in Kandro 1975 Figure 2 Correlation A.

https://github.com/GazzolaLab/PyElastica/blob/fee87b9da22e310ff925c16fdc839bf8405c51a4/elastica/rod/factory_function.py#L221-L222

 **How to fix**: change shear coefficient as `27./28.` .

**Comment by bhosale2** [comment]
Closed via #82.
